spawn-claim:
  enabled: true

  worlds:
    - world

  use-world-spawn: false

  center:
    x: 0.0
    y: 0.0
    z: 0.0

  center-yaw: 0.0
  center-pitch: 0.0

  radius-blocks: 150

  first-join:
    enabled: true
    set-bed-spawn: true
    world: "world"
    debug-force: false

  bypass-permission: "soulsmp.spawn.bypass"

  features:
    block-break: true
    block-place: true
    explosions: true
    liquids: true
    buckets: true
    interact-blocks: true
    interact-entities: true
    damage-entities: true
    pistons: true
    projectiles: true
    fishing: true

  messages:
    generic: "&cYou can't do that in Spawn."
    block-modify: "&cYou cannot modify blocks in Spawn."
    interact: "&cYou cannot interact here in Spawn."
    damage: "&cYou cannot damage entities in Spawn."
    fish: "&cYou cannot fish in Spawn."
